if [ -d $HOME/.anyenv ]; then
  export PATH="$HOME/.anyenv/bin:$PATH"
  eval "$(anyenv init -)"
fi

# rust
if [ -d $HOME/.cargo/bin ]; then
  export PATH="$HOME/.cargo/bin:$PATH"
fi

# golang
if [ -d $HOME/Development/go ]; then
  export GOPATH="$HOME/Development/go"
fi


# tools
if [ -d $HOME/Development/tools/bin ]; then
  export PATH="$HOME/Development/tools/bin:$PATH"
fi

# nvim
export XDG_CONFIG_HOME=$HOME/dotfiles
